print("Hello World!")
print("Hello Global World!")
print("Hello Visual Studio Code!")
print("Hello Visual Studio Code!")
print("Hello Global World!")
print("Hello Visual Studio Code!")
print("Hello World!")
print("Hello Global World!")
print("Hello Visual Studio Code!")
print("Hello World!")
print("Hello World!")
print("Hello World!")
print("Hello Visual Studio Code!")
print("Hello Visual Studio Code!")